openapi: 3.0.0

info:
  title: Mostanad API
  version: 1.0.0
  description: |
    API for managing documents and users in the **Mostanad** application.

    ## Authentication
    This is an internal system. Authentication details will be added later.

servers:
  - url: http://localhost:3000/api/v1
    description: Development server

tags:
  - name: Users
    description: Internal system user management
  - name: Companies
    description: Company account management
  - name: Plans
    description: SaaS Subscription Plan management
  - name: Products
    description: Product catalog management
  - name: Subscriptions
    description: Tenant subscription lifecycle management

paths:
  /users:
    $ref: './paths/users/users.yaml'
  /users/{id}:
    $ref: './paths/users/users-id.yaml'
  /companies:
    $ref: './paths/companies/companies.yaml'
  /companies/{id}:
    $ref: './paths/companies/companies-id.yaml'
  /companies/{companyId}/products/upload-catalog:
    $ref: './paths/companies/catalog.yaml'
  /companies/{companyId}/products:
    $ref: './paths/products/products.yaml'
  /products/{id}:
    $ref: './paths/products/products-id.yaml'
  /plans:
    $ref: './paths/plans/plans.yaml'
  /plans/{id}:
    $ref: './paths/plans/plans-id.yaml'
  /subscriptions:
    $ref: './paths/subscriptions/subscriptions.yaml'
  /subscriptions/{id}:
    $ref: './paths/subscriptions/subscriptions-id.yaml'

components:
  $ref: './components/components.yaml#/components'
